Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
    Enabled: false

Metrics/LineLength:
      Enabled: false
